import Head from 'next/head'
import { useEffect, useState } from 'react'

export default function Home() {
	let [dots, setDots] = useState(0);
	const generateDots = (amount: number) => {
		switch (amount) {
			case 0: return '';
			case 1: return '.';
			case 2: return '..';
			case 3: return '...';
		}
	};
	let interval: NodeJS.Timer;
	useEffect(() => {
		interval = setInterval(() => setDots(dots >= 4 ? 0 : dots++), 500);
		return () => {
			clearInterval(interval);
		}
	})

	return (
		<>
			<Head>
				<title>KevinIDJ</title>
				{/* <meta name="description" content="Generated by create next app" /> */}
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className='main-soon'>
				<h1 className='page-header-soon'>Vuelva pronto{generateDots(dots)}</h1>
			</main>
		</>
	)
}
